### ISSUE TITLE
SECURITY RISK

### ISSUE THREAD

**Issue by kemoycampbell** [yousaf446/ESM#1]
I AM NOT SURE IF YOU ARE AWARE, BUT YOU ACTUALLY INCLUDED YOUR LOGIN INFORMATION IN THE CODE AND IT IS PUBLIC ACCESSIBLE!!

       $this->cpanelHost = 'n3plcpnl0129.prod.ams3.secureserver.net';
        $this->cpanelPort = '2083';
        $this->username = 'codecron';
        $this->password = 'l!n0d3Server';

**Comment by yousaf446** [comment]
Thanks kemoy for mentioning. I used it for testing & didn't remember that I just pushed it on Github.

**Comment by kemoycampbell** [comment]
alright. Check this out https://github.com/kemoycampbell/cpanelAPI
